export interface PaginatedResult<T> { items: T[]; total: number; page: number; page_size: number }

export interface Company { id: string; name: string; short_name?: string; code: string; company_type: string; unified_credit_code?: string; legal_person?: string; address?: string; phone?: string; status: number; parent_id?: string; created_at?: string }
export interface Department { id: string; name: string; code?: string; parent_id?: string; manager_id?: string; sort_order: number; status: number }
export interface User { id: string; username: string; real_name?: string; phone?: string; email?: string; avatar_url?: string; gender: number; status: number; is_super_admin: boolean; company_id: string; department_id?: string; created_at?: string }
export interface Role { id: string; name: string; code: string; description?: string; status: number }
export interface Permission { id: string; name: string; code: string; module: string; action: string }

export interface Project { id: string; project_code: string; name: string; project_type: string; status: string; priority: number; progress: number; counterparty_company?: string; execution_unit_id?: string; partner_id?: string; enabled_modules?: Record<string, boolean> | string[]; total_budget?: number; budget_items?: Record<string, unknown>[]; actual_cost?: number; province?: string; city?: string; address?: string; longitude?: number; latitude?: number; customer_id?: string; contract_id?: string; start_date?: string; end_date?: string; actual_start_date?: string; actual_end_date?: string; project_manager_id?: string; team_members?: Record<string, unknown>; description?: string; workflow_instance_id?: string; entity_id?: string; operation_entity_id?: string; created_at?: string }
export interface Milestone { id: string; project_id: string; name: string; planned_date?: string; actual_date?: string; status: string; description?: string; sort_order: number }
export interface DailyTarget { id: string; project_id: string; target_date: string; target_content?: string; target_items?: Record<string, unknown>; completion_content?: string; completion_items?: Record<string, unknown>; overall_completion_rate: number; deviation_analysis?: string; corrective_action?: string; weather?: string; temperature?: string; recorder_id?: string; reviewer_id?: string; status: string }
export interface DailyBudget { id: string; project_id: string; budget_date: string; category: string; planned_amount?: number; actual_amount?: number; items?: Record<string, unknown>; cumulative_budget?: number; cumulative_actual?: number; budget_execution_rate?: number; variance_amount?: number; variance_reason?: string; status: string }
export interface DailyLabor { id: string; project_id: string; labor_date: string; records?: Record<string, unknown>; total_workers: number; total_regular_hours?: number; total_overtime_hours?: number; total_labor_cost?: number; recorder_id?: string; status: string }
export interface ConstructionLog { id: string; project_id: string; log_date: string; weather?: string; temperature?: string; work_content?: string; worker_count: number; equipment_used?: string; materials_used?: string; safety_status: string; quality_issues?: string; photos?: Record<string, unknown>[]; recorder_id?: string; execution_unit?: string; feedback?: string }
export interface ProcurementApproval { id: string; project_id: string; approval_no: string; procurement_type: string; title: string; description?: string; items?: Record<string, unknown>; total_amount?: number; urgency: string; expected_date?: string; budget_check?: Record<string, unknown>; attachments?: Record<string, unknown>[]; status: string }
export interface ServiceTicket { id: string; project_id?: string; ticket_no: string; service_type: string; title: string; description?: string; customer_name?: string; customer_phone?: string; customer_company?: string; priority: number; status: string; assigned_to?: string; assigned_at?: string; handling_records?: Record<string, unknown>[]; resolution?: string; completed_at?: string; customer_rating?: number; customer_feedback?: string; warranty_start?: string; warranty_end?: string; photos?: Record<string, unknown>[] }
export interface Inspection { id: string; project_id: string; ticket_id?: string; inspection_type: string; inspection_date: string; inspector_id?: string; items?: Record<string, unknown>; overall_result: string; issues_found?: string; rectification_required: boolean; rectification_deadline?: string; rectification_status: string; photos?: Record<string, unknown>[]; remark?: string }
export interface SafetyInspection { id: string; project_id: string; inspection_date: string; inspector_id?: string; inspection_type: string; hazards?: Record<string, unknown>[]; overall_level: string; photos?: Record<string, unknown>[]; rectification_deadline?: string; rectification_status: string; remark?: string }
export interface ProjectAcceptance { id: string; project_id: string; acceptance_type: string; acceptance_date: string; acceptance_unit?: string; result: string; issues?: string; sign_off_photos?: Record<string, unknown>[]; handover_docs?: Record<string, unknown>[] }

export interface Station { id: string; station_code: string; name: string; station_type: string; status: string; province?: string; city?: string; district?: string; address?: string; longitude?: number; latitude?: number; total_parking?: number; construction_cost?: number; operation_start_date?: string; landlord?: string; lease_start?: string; lease_end?: string; monthly_rent?: number; power_capacity?: number; opening_hours?: string; photos?: Record<string, unknown>[]; facilities?: Record<string, unknown>; project_id?: string; electricity_payee?: string }
  export interface Device { id: string; station_id: string; device_code: string; manufacturer?: string; model?: string; device_type: string; rated_power?: number; gun_count: number; status: string; install_date?: string; project_id?: string; total_charging_kwh: number; total_charging_count: number }
export interface ChargingOrder { id: string; order_no: string; source_order_no?: string; business_order_no?: string; order_type?: string; station_id?: string; station_name?: string; device_id?: string; gun_code?: string; device_type?: string; channel?: string; user_code?: string; enterprise_name?: string; plate_number?: string; vin?: string; gun_index: number; user_id?: string; charging_kwh?: number; energy_price?: number; service_price?: number; energy_cost?: number; service_cost?: number; original_amount?: number; discount_amount?: number; total_amount?: number; pay_amount?: number; pay_method?: string; pay_status: string; status: string; start_time?: string; end_time?: string; duration_minutes?: number; extra_data?: Record<string, unknown> }
export interface ChargingMember { id: string; member_no: string; nickname?: string; phone?: string; member_level: string; balance: number; points: number; total_charged_kwh: number; total_orders: number; status: string }
export interface FleetCustomer { id: string; fleet_name: string; fleet_code: string; contact_person?: string; contact_phone?: string; fleet_size?: number; plate_numbers?: string[]; credit_limit?: number; balance: number; total_charged_kwh: number; total_payment: number; status: string; remark?: string }
export interface FleetRecharge { id: string; fleet_id: string; recharge_no: string; amount: number; bonus_amount: number; payment_method?: string; payment_proof?: Record<string, unknown>; balance_before?: number; balance_after?: number; status: string }
export interface FleetBill { id: string; fleet_id: string; bill_no: string; period: string; total_orders: number; total_kwh?: number; total_amount?: number; net_amount?: number; deducted_from_balance: number; actual_pay_amount?: number; payment_due_date?: string; payment_status: string }
export interface FleetInvoiceRequest { id: string; fleet_id: string; request_no: string; invoice_type: string; invoice_title: string; tax_no?: string; bank_name?: string; bank_account?: string; amount?: number; status: string; invoice_id?: string; remark?: string }
export interface Partnership { id: string; partner_name: string; partner_type: string; cooperation_type: string; contact_person?: string; contact_phone?: string; contract_id?: string; start_date?: string; end_date?: string; status: string; remark?: string; detail_config?: Record<string, unknown> }
export interface RevenueSharePlan { id: string; partnership_id: string; station_id: string; period: string; total_revenue?: number; our_share_ratio?: number; our_share_amount?: number; partner_share_amount?: number; deduct_electricity: number; deduct_rent: number; deduct_maintenance: number; net_share_amount?: number; payment_due_date?: string; payment_status: string; voucher_id?: string; remark?: string }
export interface SiteProspect { id: string; name: string; province: string; city: string; district?: string; address: string; longitude?: number; latitude?: number; area_size?: number; land_type?: string; owner_name?: string; owner_phone?: string; owner_company?: string; expected_rent?: number; lease_term_months?: number; traffic_flow_score?: number; parking_demand_score?: number; competition_score?: number; power_supply_score?: number; overall_score?: number; nearby_facilities?: Record<string, unknown>; estimated_investment?: number; estimated_monthly_revenue?: number; estimated_roi_months?: number; status: string; assigned_to?: string; follow_up_records?: Record<string, unknown>[]; photos?: Record<string, unknown>[]; remark?: string }
export interface SiteVisit { id: string; site_id: string; visit_date?: string; visitors?: string; findings?: string; power_condition?: string; traffic_condition?: string; competition_nearby?: string; recommendation?: string; photos?: Record<string, unknown>[]; next_action?: string; visit_score?: number }
export interface TargetCustomer { id: string; customer_name: string; customer_type: string; source?: string; contact_person?: string; contact_phone?: string; estimated_fleet_size?: number; estimated_monthly_kwh?: number; estimated_monthly_revenue?: number; nearby_station_id?: string; follow_up_records?: Record<string, unknown>[]; current_stage: string; win_probability: number; assigned_to?: string; status: string; remark?: string }
export interface MonthlyTask { id: string; month: string; task_type: string; title: string; description?: string; assignee_id?: string; station_id?: string; priority: number; planned_start?: string; planned_end?: string; actual_start?: string; actual_end?: string; completion_rate: number; status: string; deliverables?: Record<string, unknown>; remark?: string }
  export interface ElectricityPayment { id: string; station_id: string; period: string; meter_reading_start?: number; meter_reading_end?: number; total_kwh?: number; price_segments?: Record<string, unknown>; total_amount?: number; due_date?: string; payment_date?: string; payment_status: string; project_id?: string; voucher_id?: string; remark?: string }
  export interface StationFinancial { id: string; station_id: string; month: string; total_orders: number; total_kwh?: number; total_energy_revenue?: number; total_service_revenue?: number; total_revenue?: number; electricity_cost: number; rent_cost: number; depreciation: number; maintenance_cost: number; labor_cost: number; total_cost?: number; gross_profit?: number; gross_margin?: number; project_id?: string; status: string }

export interface Account { id: string; code: string; name: string; category: string; level: number; parent_id?: string; direction: string; is_leaf: boolean; is_enabled: boolean; cash_flow_type?: string; auxiliary_types?: Record<string, unknown> }
export interface Period { id: string; period: string; start_date: string; end_date: string; status: string; closed_by?: string; closed_at?: string }
  export interface Voucher { id: string; voucher_no: string; voucher_date: string; period: string; voucher_type: string; total_debit: number; total_credit: number; line_count: number; business_type?: string; business_id?: string; source_module?: string; source_no?: string; project_id?: string; attachments?: Record<string, unknown>[]; status: string; prepared_by?: string; reviewed_by?: string; posted_by?: string; remark?: string; lines?: VoucherLine[] }
export interface VoucherLine { id: string; voucher_id: string; line_no: number; account_id: string; account_code: string; account_name: string; debit: number; credit: number; cost_center_id?: string; cost_center_type?: string; counterparty_id?: string; counterparty_name?: string; summary?: string }
export interface ArAp { id: string; type: string; business_type?: string; business_id?: string; source_no?: string; counterparty?: string; counterparty_id?: string; total_amount?: number; settled_amount: number; remaining_amount?: number; due_date?: string; overdue_days: number; status: string; voucher_id?: string; project_id?: string; contract_id?: string; remark?: string }
export interface Settlement { id: string; settlement_no: string; direction: string; counterparty?: string; counterparty_id?: string; amount?: number; payment_method?: string; bank_account?: string; settlement_date?: string; arap_ids?: string[]; voucher_id?: string; contract_id?: string; project_id?: string; remark?: string }
  export interface Invoice { id: string; invoice_type: string; direction: string; invoice_code?: string; invoice_no?: string; issue_date?: string; seller_name?: string; buyer_name?: string; amount_before_tax?: number; tax_rate?: number; tax_amount?: number; total_amount?: number; items?: Record<string, unknown>[]; check_status: string; contract_id?: string; purchase_order_id?: string; project_id?: string; voucher_id?: string; arap_id?: string; attachments?: Record<string, unknown>[] }
export interface TaxRecord { id: string; tax_type: string; period: string; declaration_date?: string; taxable_amount?: number; tax_rate?: number; tax_amount?: number; paid_amount?: number; payment_date?: string; voucher_id?: string; status: string; remark?: string }
export interface Budget { id: string; name: string; period_type: string; period: string; department_id?: string; project_id?: string; items?: Record<string, unknown>; total_budget?: number; total_used: number; total_committed: number; status: string }
export interface CostCenter { id: string; code: string; name: string; center_type: string; ref_id?: string; parent_id?: string; status: number }

export interface Supplier { id: string; name: string; code: string; category: string; contact_person?: string; contact_phone?: string; unified_credit_code?: string; bank_name?: string; bank_account?: string; rating: number; status: number; remark?: string }
export interface ProcurementRequest { id: string; pr_no: string; title: string; project_id?: string; budget_id?: string; budget_amount?: number; items?: Record<string, unknown>; total_amount?: number; urgency: string; expected_date?: string; status: string; remark?: string }
export interface PurchaseOrder { id: string; po_no: string; pr_id?: string; supplier_id?: string; supplier_name?: string; order_number?: string; project_id?: string; contract_id?: string; title: string; items?: Record<string, unknown>; total_amount?: number; received_amount: number; invoiced_amount: number; delivery_date?: string; status: string }
export interface GoodsReceipt { id: string; gr_no: string; po_id: string; project_id?: string; items?: Record<string, unknown>; total_amount?: number; received_date?: string; receiver_id?: string; quality_status: string; status: string; remark?: string }
  export interface Contract { id: string; contract_no: string; name: string; contract_type: string; party_a?: string; party_b?: string; supplier_id?: string; signing_date?: string; start_date?: string; end_date?: string; total_amount?: number; paid_amount: number; invoiced_amount: number; payment_terms?: Record<string, unknown>; key_clauses?: Record<string, unknown>; remark?: string; po_id?: string; project_id?: string; entity_id?: string; attachments?: Record<string, unknown>[]; status: string; created_at?: string; updated_at?: string }

export interface SiteDecision { id: string; site_id: string; decision_type: string; decision_date: string; decision_reason?: string; investment_amount?: number; expected_roi_months?: number; cooperate_partner?: string; cooperate_ratio?: number; approved_by?: string; status: string }
export interface ProjectPermit { id: string; project_id: string; permit_type: string; permit_no?: string; permit_name: string; issuing_authority?: string; apply_date?: string; approve_date?: string; expire_date?: string; status: string; attachments?: Record<string, unknown>[]; remark?: string }
export interface WeeklyPlan { id: string; project_id: string; week_start: string; week_end: string; week_no: number; objectives?: string; key_tasks?: string; resource_plan?: string; risk_assessment?: string; status: string; feedback?: string }
export interface DailyPlan { id: string; project_id: string; weekly_plan_id?: string; plan_date: string; tasks?: string; materials?: string; weather?: string; temperature?: string; estimated_hours?: number; assigned_to?: string; status: string }
export interface DailyFeedback { id: string; project_id: string; daily_plan_id: string; feedback_date: string; completed_tasks?: string; issues?: string; photos?: Record<string, unknown>[]; actual_hours?: number; worker_count: number; recorder_id?: string; completion_rate?: number; status: string }
export interface DailyExpense { id: string; expense_date: string; category: string; amount: number; description?: string; payer_type: string; payer_id?: string; payer_name?: string; project_id?: string; station_id?: string; receipt_photos?: Record<string, unknown>[] }
export interface FixedExpense { id: string; name: string; category: string; amount: number; frequency: string; start_date: string; end_date?: string; next_due_date?: string; payee?: string; auto_record: boolean; status: string; project_id?: string; station_id?: string }
export interface EmployeePlan { id: string; plan_date: string; employee_id: string; tasks: Record<string, unknown>; created_by_admin: boolean; status: string; completion_note?: string }
export interface WorkHour { id: string; project_id: string; employee_id: string; work_date: string; hours: number; work_type?: string; description?: string; overtime_hours: number; status: string }

export interface Notification { id: string; title: string; content: string; type: string; is_read: boolean; created_at: string }
export interface WorkflowInstance { id: string; template_id: string; title: string; status: string; created_at: string }
export interface WorkflowTemplate { id: string; name: string; module: string; steps: number }

export interface DashboardStats { active_projects: number; active_stations: number; pending_approvals: number; total_ar: number; overdue_ar: number; total_ap: number; pending_tickets: number; monthly_revenue: number; monthly_expense: number }
export interface DashboardCharts { categories: { name: string; value: number }[]; trends: { month: string; revenue: number; expense: number }[] }

export interface DailyExpenseSummary { total: number; by_category: { category: string; amount: number }[]; by_payer: { payer_type: string; amount: number }[] }

export interface LogEntry { id: string; username: string; module: string; action: string; target_type: string; target_id: string; detail: string; ip: string; created_at: string }
export interface TokenResponse { access_token: string; refresh_token: string; token_type: string; user_id: string; real_name?: string }
